export enum TenantStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  TRIAL = 'TRIAL',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum SystemRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TENANT_OWNER = 'TENANT_OWNER',
  MANAGER = 'MANAGER',
  SERVICE_ADVISOR = 'SERVICE_ADVISOR',
  TECHNICIAN = 'TECHNICIAN',
  ACCOUNTANT = 'ACCOUNTANT',
}

export enum ServiceOrderStatus {
  APPOINTMENT = 'APPOINTMENT',
  VEHICLE_ARRIVED = 'VEHICLE_ARRIVED',
  INSPECTION = 'INSPECTION',
  PREPARING_QUOTE = 'PREPARING_QUOTE',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  APPROVED = 'APPROVED',
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_INSPECTION = 'AWAITING_INSPECTION',
  READY = 'READY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum PaymentMethod {
  CASH = 'CASH',
  CREDIT_CARD = 'CREDIT_CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  WIRE_TRANSFER = 'WIRE_TRANSFER',
  OTHER = 'OTHER',
}

export enum TransactionType {
  SERVICE = 'SERVICE',
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
  DISCOUNT = 'DISCOUNT',
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum InventoryTransactionType {
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  SERVICE_USAGE = 'SERVICE_USAGE',
  RETURN = 'RETURN',
  STOCK_COUNT = 'STOCK_COUNT',
  WASTE = 'WASTE',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum FuelType {
  GASOLINE = 'GASOLINE',
  DIESEL = 'DIESEL',
  LPG = 'LPG',
  ELECTRIC = 'ELECTRIC',
  HYBRID = 'HYBRID',
}

export enum TransmissionType {
  MANUAL = 'MANUAL',
  AUTOMATIC = 'AUTOMATIC',
  SEMI_AUTOMATIC = 'SEMI_AUTOMATIC',
}

export enum SyncStatus {
  PENDING = 'PENDING',
  SYNCING = 'SYNCING',
  SYNCED = 'SYNCED',
  FAILED = 'FAILED',
  CONFLICT = 'CONFLICT',
}

export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  CUSTOMER_CREATED = 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED = 'CUSTOMER_UPDATED',
  VEHICLE_CREATED = 'VEHICLE_CREATED',
  VEHICLE_UPDATED = 'VEHICLE_UPDATED',
  SERVICE_ORDER_CREATED = 'SERVICE_ORDER_CREATED',
  SERVICE_ORDER_UPDATED = 'SERVICE_ORDER_UPDATED',
  SERVICE_ORDER_APPROVED = 'SERVICE_ORDER_APPROVED',
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_UPDATED = 'PAYMENT_UPDATED',
  INVENTORY_CHANGED = 'INVENTORY_CHANGED',
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED = 'APPOINTMENT_UPDATED',
  USER_PERMISSION_CHANGED = 'USER_PERMISSION_CHANGED',
  TENANT_CREATED = 'TENANT_CREATED',
  TENANT_UPDATED = 'TENANT_UPDATED',
}
